import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import camplogo from '../public/camplogo.png'
import profile from '../public/profile.jpg'
import sender from '../public/gal_gadot.jpg'
import event from '../public/event.jpg'
import Badge from '../public/badge.svg'
import Network from '../public/network.svg'
import { ConversationCard, Groups, Navbar, PostCard, ProfileCard, News, OppCard } from '../components'
import EventCard from '../components/EventCard'

export default function Home() {
  return (
    <>
    <Navbar/>
    <div className="bg-grey-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-6xl mx-auto px-4 py-4">
      <div className="grid grid-cols-12 gap-4">
        {/* left */}
        <div className="col-span-3 ...">
          <ProfileCard/>
          <Groups />
        </div>

        {/* middle */}
        <div className="col-span-6  ...">
          <ConversationCard />
          {/* posts */}
          <PostCard />
          <EventCard />
        </div>

        {/* right */}
        <div className="col-span-3 ...">
          <News />
          <OppCard />
          
        </div>
    </div>
      </div>
      
    </div>
    </>
  )
}
